server:
  port: 8080
  mode: debug

database:
  # DSN: Data Source Name
  # 注意 search_path=ledger,public 自动处理 schema
  dsn: "host=localhost user=finscale-user password=1234 dbname=finscale port=5433 sslmode=disable TimeZone=Asia/Shanghai search_path=ledger,public"
  max_idle_conns: 10
  max_open_conns: 100